```yml
apiVersion: v1
kind: Pod
metadata:
  name: backend-7cc6d99977-9vw8k
  namespace: chat-app
spec:
  containers:
  - name: backend
    image: vlawliet/chatapp-backend:latest
    imagePullPolicy: Always
```