apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chat-app
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: chatapp-frontend
        image: docker.io/vlawliet/chatapp-frontend:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1048576k"
            cpu: "250m"
          limits:
            memory: "1048576k"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production