apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chat-app
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      name: frontend-pod
      namespace: chat-app
      labels:
        app: frontend
    spec:
      containers:
      - name: chatapp-frontend
        image: vlawliet/chatapp-frontend:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        
        env:
        - name: NODE_ENV
          value: production
      
